sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t skadd88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skadd88/docker-react npm run test
